### ISSUE TITLE
how to properly use napari-s3zarr ?

### ISSUE THREAD

**Issue by romainGuiet** [tlambert03/napari-s3zarr#3]
Hi @tlambert03 , Hi @GenevieveBuckley ,

I just tried to use your napari-s3zarr package and I'm not sure how I should use it. 

At EPFL we have our own S3 storage, where I dropped a zarr. 
I have the the read-only bucket "hash", the access key and secret key but I'm not sure what I should do with them !

From the s3 I get the zarr link is https://s3.epfl.ch/12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/

I saw in [s3zarr.py](https://github.com/tlambert03/napari-s3zarr/blob/master/napari_s3zarr/s3zarr.py) that the path should start with` s3: ` so I tried with : 

`napari s3:12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/`
also tried 
`napari s3:s3.epfl.ch/12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/`

napari opens, popup to select , napari builtins, napari-ome-zarr or s3zarr which I selected and then get the  error : 
```
(ome_ngff) C:\Users\guiet>napari s3:s3.epfl.ch/12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/
Traceback (most recent call last):
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\qt_viewer.py", line 830, in _qt_open
    self.viewer.open(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1024, in open
    layers = self._open_or_raise_error(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1146, in _open_or_raise_error
    raise MultipleReaderError(
napari.errors.reader_errors.MultipleReaderError: Multiple plugins found capable of reading s3:s3.epfl.ch/12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/. Select plugin from {'s3zarr': 's3zarr', 'napari': 'napari builtins', 'napari-ome-zarr': 'napari-ome-zarr'} and pass to reading function e.g. `viewer.open(..., plugin=...)`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\guiet\.conda\envs\ome_ngff\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\__main__.py", line 561, in main
    _run()
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\__main__.py", line 341, in _run
    viewer._window._qt_viewer._qt_open(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\qt_viewer.py", line 848, in _qt_open
    handle_gui_reading(filenames, self, stack, **kwargs)
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\dialogs\qt_reader_dialog.py", line 199, in handle_gui_reading
    open_with_dialog_choices(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\dialogs\qt_reader_dialog.py", line 292, in open_with_dialog_choices
    qt_viewer.viewer.open(paths, stack=stack, plugin=plugin_name, **kwargs)
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1014, in open
    self._add_layers_with_plugins(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\plugins\io.py", line 114, in read_data_with_plugins
    raise ValueError(
ValueError: Plugin 's3zarr' does not support file(s) ['C:\\Users\\guiet\\s3:s3.epfl.ch\\12092-127a2c5216de10513f28977152b492d9\\Test_zarr\\ome-tiff.companion.ome_lvl_0.ome.zarr']
```

But as I'm discovering both zarr and s3 , I'm not really sure what i should try next...  

Thank you in advance for your answer,

Best,

Romain

**Comment by tlambert03** [comment]
Hey @romainGuiet, thanks for your note.

>I saw in [s3zarr.py](https://github.com/tlambert03/napari-s3zarr/blob/master/napari_s3zarr/s3zarr.py) that the path should start withs3: so I tried with :
> napari s3:12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/

You were on the right track there by looking at that file, but note also that it asserts that `path.endswith(".zarr")` ... and your path does not... it ends with `.zarr/`.  So you should try removing that trailing slash.  (if that works for you, you could make a pr that converts this to `path.rstrip("/").endswith(".zarr"):`)

**Comment by romainGuiet** [comment]
Hi @tlambert03 ,

thank you for your swift answer.

>You were on the right track there by looking at that file, but note also that it asserts that path.endswith(".zarr")

I think it's a different issue, because if I run without or with the `/`
`napari s3:12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr`
or
`napari s3:12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/`
in both case I have the pop up window which proposes s3zaar
<img width="609" alt="image" src="https://user-images.githubusercontent.com/8309560/205239481-f3ae5794-302c-4f0e-bd68-27ae54ae3f72.png">

so my guess is that it passes the endswith() test because if I run while adding `/0/`: 
`napari s3:12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/0/`
(cf will reply on f[orum.iamge.sc ](https://forum.image.sc/t/ngff-converter-napari-ome-zarr-ome-zarr/74435/4?u=romainguiet)) the popup doesn't contain s3zarr and the error is different and becomes : 

```
(ome_ngff) C:\Users\guiet>napari s3:12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/0/
Traceback (most recent call last):
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1126, in _open_or_raise_error
    added = self._add_layers_with_plugins(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1216, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\plugins\io.py", line 104, in read_data_with_plugins
    raise ValueError(
ValueError: There is no registered plugin named 'napari-ome-zarr'.
Names of plugins offering readers are: {'s3zarr'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\qt_viewer.py", line 830, in _qt_open
    self.viewer.open(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1024, in open
    layers = self._open_or_raise_error(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\components\viewer_model.py", line 1135, in _open_or_raise_error
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried opening with napari-ome-zarr, but failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\guiet\.conda\envs\ome_ngff\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\__main__.py", line 561, in main
    _run()
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\__main__.py", line 341, in _run
    viewer._window._qt_viewer._qt_open(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\qt_viewer.py", line 838, in _qt_open
    handle_gui_reading(
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\dialogs\qt_reader_dialog.py", line 188, in handle_gui_reading
    readers = prepare_remaining_readers(paths, plugin_name, error)
  File "C:\Users\guiet\.conda\envs\ome_ngff\lib\site-packages\napari\_qt\dialogs\qt_reader_dialog.py", line 243, in prepare_remaining_readers
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried to read s3:12092-127a2c5216de10513f28977152b492d9/Test_zarr/ome-tiff.companion.ome_lvl_0.ome.zarr/0/ with plugin napari-ome-zarr, because it was associated with that file extension/because it is the only plugin capable of reading that path, but it gave an error. Try associating a different plugin or installing a different plugin for this kind of file.
```

Best

R

**Comment by romainGuiet** [comment]
Would you have a s3 dataset link that I could test ? So I could check if the issue is not due to my dataset or s3 settings ?

Best,

Romain

**Comment by tlambert03** [comment]
Ok, in that case, I'd recommend just trying to use dask.array.from_zarr directly to see what the error is (sorry the exception messages are useless)

Note that this plugin is essentially just a one liner that calls https://docs.dask.org/en/stable/generated/dask.array.from_zarr.html

`return [(da.from_zarr(path, storage_options={"anon": True}),)]`
